version: "3.9"
services:
  # this is no microservice - just for the joined openAPI config
  openapi-ui:
    environment:
      - API_NAME=Example API-Gateway
    image: "openapi-ui:latest"
    ports:
      - "8005:8080"
    volumes:
      - ../config/swagger-ui:/root/public
  # microserives start here
  advanced:
    image: "advanced:latest"
    ports:
      - "8010:8080"
  dotnetapi:
    image: "dotnetapi:latest"
    ports:
      - "8011:8080"
  greeter:
    image: "greeter:latest"
    ports:
      - "8012:8080"
  mathservice:
    image: "mathservice:latest"
    ports:
      - "8013:8080"
  task-api:
    image: "task-api:latest"
    ports:
      - "8014:8080"
  tsoaapi:
    image: "tsoaapi:latest"
    ports:
      - "8015:8080"
  springapi:
    image: "springapi:latest"
    ports:
      - "8016:8080"
